
package com.caoruiqun.admin.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SealServiceImplService", targetNamespace = "http://impl.service.seal.bjpowernode.com/", wsdlLocation = "http://localhost:8080/e-seal/services/sealService?wsdl")
public class SealServiceImplService
    extends Service
{

    private final static URL SEALSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEALSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SEALSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.seal.bjpowernode.com/", "SealServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/e-seal/services/sealService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEALSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SEALSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SealServiceImplService() {
        super(__getWsdlLocation(), SEALSERVICEIMPLSERVICE_QNAME);
    }

    public SealServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEALSERVICEIMPLSERVICE_QNAME, features);
    }

    public SealServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SEALSERVICEIMPLSERVICE_QNAME);
    }

    public SealServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEALSERVICEIMPLSERVICE_QNAME, features);
    }

    public SealServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SealServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SealServiceImpl
     */
    @WebEndpoint(name = "SealServiceImplPort")
    public SealServiceImpl getSealServiceImplPort() {
        return super.getPort(new QName("http://impl.service.seal.bjpowernode.com/", "SealServiceImplPort"), SealServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SealServiceImpl
     */
    @WebEndpoint(name = "SealServiceImplPort")
    public SealServiceImpl getSealServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.seal.bjpowernode.com/", "SealServiceImplPort"), SealServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEALSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SEALSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SEALSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
