
package com.caoruiqun.admin.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SealServiceImpl", targetNamespace = "http://impl.service.seal.bjpowernode.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SealServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pdfSeal", targetNamespace = "http://impl.service.seal.bjpowernode.com/", className = "com.bjpowernode.seal.service.impl.PdfSeal")
    @ResponseWrapper(localName = "pdfSealResponse", targetNamespace = "http://impl.service.seal.bjpowernode.com/", className = "com.bjpowernode.seal.service.impl.PdfSealResponse")
    @Action(input = "http://impl.service.seal.bjpowernode.com/SealServiceImpl/pdfSealRequest", output = "http://impl.service.seal.bjpowernode.com/SealServiceImpl/pdfSealResponse")
    public String pdfSeal(
            @WebParam(name = "arg0", targetNamespace = "")
                    CreditorVO arg0);

}
